name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.PLUGIN }} group ${{ matrix.TEST_GROUP }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        PLUGIN: [sbt-coursier, sbt-lm-coursier]
        TEST_GROUP: [1, 2]
    steps:
    - name: Don't convert LF to CRLF during checkout
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Checkout adpi2/coursier
      uses: actions/checkout@v3
      with:
        repository: adpi2/coursier
        ref: sbt-plugins-maven-path
        path: coursier
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3.0
      with:
        jvm: 8
        apps: sbt
    - name: Build coursier
      shell: bash
      run: |
        cd coursier
        ./mill 'util.jvm[2.12.17].publishLocal'
        ./mill 'util.jvm[2.13.6].publishLocal'
        ./mill 'core.jvm[2.12.17].publishLocal'
        ./mill 'core.jvm[2.13.6].publishLocal'
        ./mill 'cache.jvm[2.12.17].publishLocal'
        ./mill 'cache.jvm[2.13.6].publishLocal'
        ./mill 'coursier.jvm[2.12.17].publishLocal'
        ./mill 'coursier.jvm[2.13.6].publishLocal'
        ./mill 'sbt-maven-repository.jvm[2.12.17].publishLocal'
        ./mill 'sbt-maven-repository.jvm[2.13.6].publishLocal'
        ./mill 'proxy-setup.publishLocal'
    - run: scripts/ci.sh
      shell: bash
      env:
        PLUGIN: ${{ matrix.PLUGIN }}
        TEST_GROUP: ${{ matrix.TEST_GROUP }}

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
          apps: sbt
      - uses: olafurpg/setup-gpg@v3
      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
